### ISSUE TITLE
Failed to resolve gradle implementation 

### ISSUE THREAD

**Issue by amuna** [Commit451/mailgun#14]
`implementation "com.github.Commit451:mailgun:1.2.1"`

When adding the above live to gradle dependency, the following error is shown:

Failed to resolve: com.github.Commit451:mailgun:1.2.1

**Comment by Jawnnypoo** [comment]
Hey there, did you add the Jitpack URL as well?

**Comment by amuna** [comment]
I had it in buildscript and not in allprojects. Looks like it is resolved. Thank you.
