### ISSUE TITLE
How to send an image attachment 

### ISSUE THREAD

**Issue by Ramkesh9** [Commit451/mailgun#3]
Thank you for a awsome library , please let me know if their any posiblity for if i can send any image attachment alongwith text.

Thank you .

**Comment by Jawnnypoo** [comment]
README has been updated with an example, you will just need to change your RequestBody to be the image instead of a text file. You can see more in the OkHttp docs.

**Comment by Ramkesh9** [comment]
Hi Jawnnypoo, thanks for responding,
The build was successfull, but i am unable to run the app to device . because run button is grayed out. don't know why.
please help me how to address and solve this issue .
![img_20190127_004412](https://user-images.githubusercontent.com/25117929/51791711-d3aebd00-21cc-11e9-8a7d-9527d8adad7d.png)

**Comment by Jawnnypoo** [comment]
Hmm, I am confused. From the screenshot, it looks like you are just running this library as an Android project in Android Studio. You need to use Gradle to pull in this library to your Android app project.

**Comment by Ramkesh9** [comment]
I also used your library as gradle importing, while compiling few lines from your readme text file, but their details are missing to configure the flow to hit a email.
Could you able to send me any example or complete instructions to configuration the mail send process?
Your readme file is incomplete.
